SELECT TOP (1000) [Arac_ID]
      ,[Arac_Turu]
      ,[Arac_Markasi]
      ,[Arac_Modeli]
      ,[Arac_Uretim_Baslangic_Tarihi]
      ,[Arac_Uretim_Bitis_Tarihi]
      ,[Arac_Maliyet_Tutari]
      ,[Arac_Satis_Durumu]
  FROM [AracFabrikasi].[dbo].[AracBilgileri]
